### ISSUE TITLE
Add Support to Gutenberg

### ISSUE THREAD

**Issue by lotharthesavior** [janboddez/import-bookmarks#3]
@janboddez 

I noticed, while testing the plugin, that it create posts that end up creating the default post content. We could add "links" in case the "block editor" is active in the WordPress instance.

Let me know if this is something that you consider for this plugin.

**Comment by janboddez** [comment]
@lotharthesavior Yeah, supporting Gutenberg definitely makes sense. I'm not too familiar with it, yet... (~~Didn't even know there was a core/link block.~~ Guess wrapping both paragraphs in Gutenberg HTML comments would suffice?)

'Classic' posts could be improved, too: the link text could be set to the web page title and links made clickable. (Right now the post content will simply be a description, if any—seriously, who ever adds one to their bookmarks anyway?—and/or a plain URL on a line of its own.)

**Comment by janboddez** [comment]
Added the wrapper bits, then took them out again and went with a filter hook. Anyone can now implement their own version of:
```
add_filter( 'import_bookmarks_post_content', function( $post_content, $bookmark, $post_type ) {
    // Somehow edit `$post_content`.
    return $post_content;
}, 10, 3 );
```
Add to `functions.php` or add-on plugin.
